### ISSUE TITLE
vulkaninfo compute not working on linux.

### ISSUE THREAD

**Issue by splace** [vulkan-go/demos#15]
i get this...

````
fatal error: unexpected signal during runtime execution
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x0]

runtime stack:
runtime.throw(0x52b296, 0x2a)
	/usr/lib64/golang/src/runtime/panic.go:774 +0x72
runtime.sigpanic()
	/usr/lib64/golang/src/runtime/signal_unix.go:378 +0x47c
runtime.asmcgocall(0xc000080400, 0x0)
	/usr/lib64/golang/src/runtime/asm_amd64.s:659 +0x70

goroutine 1 [syscall]:
runtime.cgocall(0x4d9060, 0xc0000add28, 0x4a6859)
	/usr/lib64/golang/src/runtime/cgocall.go:128 +0x5b fp=0xc0000adcf8 sp=0xc0000adcc0 pc=0x40c1fb
github.com/vulkan-go/vulkan._Cfunc_callVkDestroySurfaceKHR(0x1e795a0, 0x0, 0x0)
	_cgo_gotypes.go:6073 +0x45 fp=0xc0000add28 sp=0xc0000adcf8 pc=0x49d295
github.com/vulkan-go/vulkan.DestroySurface.func1(0x1e795a0, 0x0, 0x0)
	/home/simon/go/src/github.com/vulkan-go/vulkan/vulkan.go:1359 +0xc4 fp=0xc0000add60 sp=0xc0000add28 pc=0x4a6b14
github.com/vulkan-go/vulkan.DestroySurface(0x1e795a0, 0x0, 0x0)
	/home/simon/go/src/github.com/vulkan-go/vulkan/vulkan.go:1359 +0x3f fp=0xc0000add88 sp=0xc0000add60 pc=0x4a5fff
github.com/vulkan-go/demos/vulkaninfo.NewVulkanDevice(0x5e7ac0, 0x0, 0x0, 0x0, 0x0)
	/home/simon/go/src/github.com/vulkan-go/demos/vulkaninfo/vulkaninfo.go:63 +0x462 fp=0xc0000adf20 sp=0xc0000add88 pc=0x4d3892
main.main()
	/home/simon/go/src/github.com/vulkan-go/demos/vulkaninfo/vulkaninfo_compute/main.go:19 +0x70 fp=0xc0000adf60 sp=0xc0000adf20 pc=0x4d7d90
runtime.main()
	/usr/lib64/golang/src/runtime/proc.go:203 +0x21e fp=0xc0000adfe0 sp=0xc0000adf60 pc=0x4355be
runtime.goexit()
	/usr/lib64/golang/src/runtime/asm_amd64.s:1357 +0x1 fp=0xc0000adfe8 sp=0xc0000adfe0 pc=0x45db41
exit status 2

````
bit opaque but i figured it asking for swapchain in vulkaninfo.go wasn't right for term output, and fixed by commenting out...
````
...
	PQueuePriorities: []float32{1.0},
	}}
	deviceExtensions := []string{
// XXX		"VK_KHR_swapchain\x00",
	}
	deviceCreateInfo := &vk.DeviceCreateInfo{
		SType:                   vk.StructureTypeDeviceCreateInfo,
...
````

**Comment by soypat** [comment]
I am getting the following on linux, and commenting said line does not help.
```
$ go run main.go 
panic: vulkan: error loading default getProcAddr

goroutine 1 [running]:
main.orPanic({0x4d62e0?, 0xc000016440?})
        /home/pato/src/ongoing/demos/vulkaninfo/vulkaninfo_compute/main.go:29 +0xe6
main.main()
        /home/pato/src/ongoing/demos/vulkaninfo/vulkaninfo_compute/main.go:17 +0x27
exit status 2
```

**Comment by neurlang** [comment]
I got it working on my fork

**Comment by ktamail666** [comment]
I know this thread is old, but it works for me with NVIDIA. This commit: 189c453
go version go1.23.1
╭────────────────────────────────────────────────────────────────────────╮
│               VULKAN PROPERTIES AND SURFACE CAPABILITES                │
├────────────────────────┬───────────────────────────────────────────────┤
│ Physical Device Name   │ NVIDIA GeForce GTX 1660                       │
│ Physical Device Vendor │ 10de                                          │
│ Physical Device Type   │ Discrete GPU                                  │
│ Physical GPUs          │ 1                                             │
│ API Version            │ 1.3.289                                       │
│ API Version Supported  │ 1.3.289                                       │
│ Driver Version         │ 565.228.64 

...
